apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
  namespace: kubevirt-csi-driver
data:
  infraClusterNamespace: $INFRA_CLUSTER_TENANT_NAMESPACE
  infraClusterLabels: csi-driver/cluster=$TENANT_CLUSTER_NAME
